artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/paultimothymooney/blood-cells/
  local_data_file: artifacts/data_ingestion/BloodCell.zip
  unzip_dir: artifacts/data_ingestion
  unzipped_data_dir: artifacts/data_ingestion/BloodCell


